export { default as AddProductModal } from './modal/AddProduct.vue'
export { default as DeleteProductModal } from './modal/DeleteProduct.vue'
export { default as Loading } from './Loading/index.vue'
export { default as Toast } from './toast/Toast.vue'
export { default as ConfirmPay } from './modal/ConfirmPay.vue'
export { default as SearchProduct } from './modal/SearchProduct.vue'
